apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-home-etc-pcscf
spec:
  capacity:
    storage: 200Mi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /data2/retain/pcscf/etc
    server: 192.168.33.185
    readOnly: false
