apiVersion: v1
kind: Service
metadata:
  name: pcscf-udp
  labels:
    app: pcscf-metric
spec:
  type: LoadBalancer
  ports:
    - name: extern-port-udp
      protocol: UDP
      port: 5011
      targetPort: extern-udp
    - name: extern-port-tcp
      protocol: TCP
      port: 5031
      targetPort: extern-tcp
    - name: web-metric
      protocol: TCP
      port: 8000
      targetPort: web-metric
  selector:
    app: pcscf-pod
    #sessionAffinity: ClientIP